title: root@gdifiore
description: Programming and security blog
author: gdifiore
email: difioregabe@gmail.com
github_username:  gdifiore

baseurl: "/blog"
markdown: kramdown
highlighter: rouge
theme: minima
